# Generated by Django 5.2.7 on 2026-02-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_preference_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='profile_photos/'),
            preserve_default=False,
        ),
    ]
